# Use root/example as user/password credentials
version: '3.1'

services:
  mariadb:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: typeorm-api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - '8080:80'
    volumes:
      - /sessions

  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'
      - '1025:25'
volumes:
  mysql_data:
